class CreatePokeparties < ActiveRecord::Migration
  def change
    create_table :pokeparties do |t|
      t.string :party
      t.integer :battle
      t.integer :win
      t.string :battletype
      t.string :rule
      t.string :shooter
      t.text :strategic
      t.string :name1
      t.string :characteristic1
      t.string :personality1
      t.string :skill1_1
      t.string :skill1_2
      t.string :skill1_3
      t.string :skill1_4
      t.string :belonging1
      t.integer :efforth1
      t.integer :efforta1
      t.integer :effortb1
      t.integer :effortc1
      t.integer :effortd1
      t.integer :efforts1
      t.string :role1
      t.text :detail1
      t.string :name2
      t.string :characteristic2
      t.string :personality2
      t.string :skill2_1
      t.string :skill2_2
      t.string :skill2_3
      t.string :skill2_4
      t.string :belonging2
      t.integer :efforth2
      t.integer :efforta2
      t.integer :effortb2
      t.integer :effortc2
      t.integer :effortd2
      t.integer :efforts2
      t.string :role2
      t.text :detail2
      t.string :name3
      t.string :characteristic3
      t.string :personality3
      t.string :skill3_1
      t.string :skill3_2
      t.string :skill3_3
      t.string :skill3_4
      t.string :belonging3
      t.integer :efforth3
      t.integer :efforta3
      t.integer :effortb3
      t.integer :effortc3
      t.integer :effortd3
      t.integer :efforts3
      t.string :role3
      t.text :detail3
      t.string :name4
      t.string :characteristic4
      t.string :personality4
      t.string :skill4_1
      t.string :skill4_2
      t.string :skill4_3
      t.string :skill4_4
      t.string :belonging4
      t.integer :efforth4
      t.integer :efforta4
      t.integer :effortb4
      t.integer :effortc4
      t.integer :effortd4
      t.integer :efforts4
      t.string :role4
      t.text :detail4
      t.string :name5
      t.string :characteristic5
      t.string :personality5
      t.string :skill5_1
      t.string :skill5_2
      t.string :skill5_3
      t.string :skill5_4
      t.string :belonging5
      t.integer :efforth5
      t.integer :efforta5
      t.integer :effortb5
      t.integer :effortc5
      t.integer :effortd5
      t.integer :efforts5
      t.string :role5
      t.text :detail5
      t.string :name6
      t.string :characteristic6
      t.string :personality6
      t.string :skill6_1
      t.string :skill6_6
      t.string :skill6_3
      t.string :skill6_4
      t.string :belonging6
      t.integer :efforth6
      t.integer :efforta6
      t.integer :effortb6
      t.integer :effortc6
      t.integer :effortd6
      t.integer :efforts6
      t.string :role6
      t.text :detail6

      t.timestamps
    end
  end
end
